/**
 */
package org.pdulvp.data.table.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.pdulvp.data.table.util.TableAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class TableItemProviderAdapterFactory extends TableAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
  /**
   * This keeps track of the root adapter factory that delegates to this adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComposedAdapterFactory parentAdapterFactory;

  /**
   * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IChangeNotifier changeNotifier = new ChangeNotifier();

  /**
   * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Collection<Object> supportedTypes = new ArrayList<Object>();

  /**
   * This constructs an instance.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableItemProviderAdapterFactory() {
    supportedTypes.add(IEditingDomainItemProvider.class);
    supportedTypes.add(IStructuredItemContentProvider.class);
    supportedTypes.add(ITreeItemContentProvider.class);
    supportedTypes.add(IItemLabelProvider.class);
    supportedTypes.add(IItemPropertySource.class);
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DTable} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DTableItemProvider dTableItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DTable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDTableAdapter() {
    if (dTableItemProvider == null) {
      dTableItemProvider = new DTableItemProvider(this);
    }

    return dTableItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DAttribute} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DAttributeItemProvider dAttributeItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDAttributeAdapter() {
    if (dAttributeItemProvider == null) {
      dAttributeItemProvider = new DAttributeItemProvider(this);
    }

    return dAttributeItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DKey} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DKeyItemProvider dKeyItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DKey}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDKeyAdapter() {
    if (dKeyItemProvider == null) {
      dKeyItemProvider = new DKeyItemProvider(this);
    }

    return dKeyItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DNamedElement} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DNamedElementItemProvider dNamedElementItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DNamedElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDNamedElementAdapter() {
    if (dNamedElementItemProvider == null) {
      dNamedElementItemProvider = new DNamedElementItemProvider(this);
    }

    return dNamedElementItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DTablePkg} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DTablePkgItemProvider dTablePkgItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DTablePkg}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDTablePkgAdapter() {
    if (dTablePkgItemProvider == null) {
      dTablePkgItemProvider = new DTablePkgItemProvider(this);
    }

    return dTablePkgItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DKeyValue} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DKeyValueItemProvider dKeyValueItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DKeyValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDKeyValueAdapter() {
    if (dKeyValueItemProvider == null) {
      dKeyValueItemProvider = new DKeyValueItemProvider(this);
    }

    return dKeyValueItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DReference} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DReferenceItemProvider dReferenceItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDReferenceAdapter() {
    if (dReferenceItemProvider == null) {
      dReferenceItemProvider = new DReferenceItemProvider(this);
    }

    return dReferenceItemProvider;
  }

  /**
   * This keeps track of the one adapter used for all {@link org.pdulvp.data.table.DFeature} instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DFeatureItemProvider dFeatureItemProvider;

  /**
   * This creates an adapter for a {@link org.pdulvp.data.table.DFeature}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter createDFeatureAdapter() {
    if (dFeatureItemProvider == null) {
      dFeatureItemProvider = new DFeatureItemProvider(this);
    }

    return dFeatureItemProvider;
  }

  /**
   * This returns the root adapter factory that contains this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComposeableAdapterFactory getRootAdapterFactory() {
    return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
  }

  /**
   * This sets the composed adapter factory that contains this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
    this.parentAdapterFactory = parentAdapterFactory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object type) {
    return supportedTypes.contains(type) || super.isFactoryForType(type);
  }

  /**
   * This implementation substitutes the factory itself as the key for the adapter.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Adapter adapt(Notifier notifier, Object type) {
    return super.adapt(notifier, this);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object adapt(Object object, Object type) {
    if (isFactoryForType(type)) {
      Object adapter = super.adapt(object, type);
      if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
        return adapter;
      }
    }

    return null;
  }

  /**
   * This adds a listener.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void addListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.addListener(notifyChangedListener);
  }

  /**
   * This removes a listener.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void removeListener(INotifyChangedListener notifyChangedListener) {
    changeNotifier.removeListener(notifyChangedListener);
  }

  /**
   * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void fireNotifyChanged(Notification notification) {
    changeNotifier.fireNotifyChanged(notification);

    if (parentAdapterFactory != null) {
      parentAdapterFactory.fireNotifyChanged(notification);
    }
  }

  /**
   * This disposes all of the item providers created by this factory. 
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void dispose() {
    if (dTableItemProvider != null) dTableItemProvider.dispose();
    if (dFeatureItemProvider != null) dFeatureItemProvider.dispose();
    if (dAttributeItemProvider != null) dAttributeItemProvider.dispose();
    if (dReferenceItemProvider != null) dReferenceItemProvider.dispose();
    if (dKeyItemProvider != null) dKeyItemProvider.dispose();
    if (dNamedElementItemProvider != null) dNamedElementItemProvider.dispose();
    if (dTablePkgItemProvider != null) dTablePkgItemProvider.dispose();
    if (dKeyValueItemProvider != null) dKeyValueItemProvider.dispose();
  }

}
